#!/usr/bin/env bash

# Use vulkan d3d renderer.
"$WINELOADER" reg add "HKCU\\Software\\Wine\\Direct3D" /v "renderer" /t "REG_SZ" /d "vulkan" /f

# Populate .cache/wine and install wine-gecko.
geckos=( "wine-gecko-2.47.2-x86.msi" "wine-gecko-2.47.2-x86_64.msi" )
winecache="${HOME}/.cache/wine"
for g in "${geckos[@]}"; do
    if [[ -n "$SNAP_USER_COMMON" ]]; then
        winecache="${XDG_CACHE_HOME}/wine"
        mkdir -p "$winecache"
        cp -f "${SNAP}/data/${g}" "$winecache"
    fi
    "$WINELOADER" msiexec /i "${winecache}/${g}"
done

# Match language UI to system locale.
export LC_ALL="$LANG"

# # Set default DPI.
# if [[ -z "$WINEDPI" ]]; then
#     export WINEDPI=108
# fi

# Set Winver to 10.
"$WINELOADER" winecfg /v win10
