name: cog-unofficial
title: Cog (via WINE)
# base: core22 # problems with bindtextdomain.so:
# ERROR: ld.so: object '/snap/saymore-unofficial/17/gnome-platform/$LIB/bindtextdomain.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
# core20 ideas from https://github.com/mmtrt/notepad-plus-plus
base: core20
version: '1.3.6' # matches installer version below
grade: stable
summary: Compare languages using statistical and comparative linguistics techniques.
description: |
  Cog is a tool for comparing languages using lexicostatistics and comparative linguistics techniques. It can be used to automate much of the process of comparing word lists from different language varieties.

  The goal of Cog is to provide a framework for experimenting with different techniques for language variety comparison. It is intended to be used iteratively: run a comparison, analyze the results, refine the process, run the comparison again, and so on. Most steps in the process can be tailored. It currently only supports a few comparison techniques, but we hope to include many more in the future.
confinement: devmode # strict
license: MIT
website: https://github.com/wasta-linux/cog-snap
contact: nate_marti@sil.org
issues: https://github.com/wasta-linux/cog-snap/issues
icon: snap/gui/cog-unofficial.png
architectures:
  - amd64

environment:
  # SOMMELIER_NO_THEME: "true" # avoid crash b/c of Light theme
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc
  TRICKS: "fontsmooth=rgb corefonts dotnet48 vkd3d"
  # WINEARCH: "win64" # sommelier default
  WINEDLLOVERRIDES: "mscoree=n;" # Prevent pop-up about Wine Mono

apps:
  cog-unofficial:
    extensions: [gnome-3-38]
    command: bin/sommelier run-exe
    environment:
      INSTALL_EXE: "${SNAP}/data/Cog-1.3.6-Setup.exe"
      INSTALL_FLAGS: "/passive"
      RUN_EXE: "C:/Program Files/SIL/Cog/Cog.exe"

  kill-procs:
    extensions: [gnome-3-38]
    command: bin/kill-procs

  list-procs:
    extensions: [gnome-3-38]
    command: bin/list-procs
  
  watch-procs:
    extensions: [gnome-3-38]
    command: bin/watch-procs

  remove-wine-prefix:
    extensions: [gnome-3-38]
    command: bin/remove-wine-prefix

  wine:
    extensions: [gnome-3-38]
    command: bin/sommelier $WINELOADER

  winecfg:
    extensions: [gnome-3-38]
    command: bin/sommelier winecfg

  winetricks:
    extensions: [gnome-3-38]
    command: bin/sommelier winetricks

plugs:
  # something that allows "ptrace" is needed for confinement to work; use --devmode as a workaround
  audio-playback:
  desktop:
  desktop-legacy:
  home:
  network:
  removable-media:
  wayland:
  x11:

  wine-runtime-c20:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core20
  wine-7-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-stable-core20

parts:
  data:
    plugin: dump
    source: data/
    organize:
      "*": data/
    stage:
      - data

  debs:
    plugin: nil
    stage-packages:
      - procps
      - zstd
    prime:
      - bin/kill
      - usr/bin/pgrep
      - usr/bin/pkill
      - usr/bin/watch
      - usr/bin/unzstd
      - usr/bin/zstd

  # This reverts changes from https://github.com/snapcore/snapcraft/pull/3586
  fix-fontconfig:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i '/snap-package/,+1d' $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch

  # Ref: https://github.com/mmtrt/notepad-plus-plus
  fix-bindtext:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -2 | head -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch

  hooks:
    plugin: dump
    source: hooks/
    organize:
      "*": sommelier/hooks/
    stage:
      - sommelier

  scripts:
    plugin: dump
    source: scripts/
    organize:
      "*": bin/
    stage:
      - bin

  sommelier-core:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "1.0"
    # source: https://github.com/mmtrt/sommelier-core.git # to make core20 work
    # source-branch: "core20"
    override-prime: |
      # craftctl default # core22
      snapcraftctl prime # core20

      # Don't let yad dialogs stay always-on-top.
      sed -r -i 's|(yad.*) --on-top|\1|g' bin/sommelier
      # # Remove annoying yad dialog for interactive MSI install.
      # sed -r -i 's|(yes.*Installing .*EXE_NAME.*)|# \1|' bin/sommelier
      # sed -r -i 's|(.*INSTALL_YAD_PID)|# \1|g' bin/sommelier

      # Add init-only command.
      sed -r -i 's|(\s+)(init_wine)$|\1\2\n\1if [[ $INIT == '1' ]]; then exit 0; fi|' bin/sommelier
